<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>CodeChavez.Repository.Pattern</PackageId>
		<Title>CodeChavez Repository Pattern Library</Title>
		<Authors>Victor A Chavez</Authors>
		<Product>CodeChavez.Repository.Pattern</Product>
		<Version>10.0.1</Version>
		<Copyright>2020-2026</Copyright>
		<Description>Has some useful extension and utilities that allow for every day development</Description>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/codechavez/codechavez.repository.pattern</PackageProjectUrl>
		<RepositoryUrl>https://github.com/codechavez/codechavez.repository.pattern</RepositoryUrl>
		<PackageLicenseFile></PackageLicenseFile>
		<PackageTags>CodeChavez,Repository,Pattern,Common,Helpers,Utilities,.net</PackageTags>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="CodeChavez.Common" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
		<PackageReference Include="MongoDB.Bson" Version="3.7.1" />
	</ItemGroup>

</Project>
